# wrangler.toml (wrangler v3.88.0^)
name = "taskify"
main = "worker/src/index.ts"
compatibility_date = "2024-03-01"
workers_dev = true

[assets]
directory = "taskify-pwa/dist"
binding = "ASSETS"

[triggers]
crons = ["*/1 * * * *"]

[observability.logs]
enabled = true

[vars]
VAPID_PUBLIC_KEY = "BA5BrwPUO-j5WzaaPe28CApexdCiLMHgHrh40LoXyz_OmA21gId1yw5IxWqpIOVEnKGiXfI0FEiFDr1Kl8rj6Dw"
VAPID_SUBJECT = "mailto: dev@solife.me"

[[kv_namespaces]]
binding = "TASKIFY_DEVICES"
id = "c22ac7468ada4612b14690ecfebef904"

[[kv_namespaces]]
binding = "TASKIFY_REMINDERS"
id = "03a8da2b890b4d33b7ddc9273ada7868"

[[kv_namespaces]]
binding = "TASKIFY_PENDING"
id = "448d7dc7170c4aff81c2a58c5e07e739"

[[kv_namespaces]]
binding = "VAPID_PRIVATE_KEY"
id = "45bbad6e354443ff9b101d61a27e5dd9"

[[d1_databases]]
binding = "TASKIFY_DB"
database_name = "taskify-notifications"
# TODO: replace with your D1 database ID after running `wrangler d1 create`
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "worker/migrations"
