name = "taskify"
main = "worker/src/index.ts"
compatibility_date = "2024-03-01"
workers_dev = true

[assets]
directory = "taskify-pwa/dist"
binding = "ASSETS"

[triggers]
crons = ["*/1 * * * *"]

[[kv_namespaces]]
binding = "TASKIFY_DEVICES"
id = "c22ac7468ada4612b14690ecfebef904"

[[kv_namespaces]]
binding = "TASKIFY_REMINDERS"
id = "03a8da2b890b4d33b7ddc9273ada7868"

[[kv_namespaces]]
binding = "TASKIFY_PENDING"
id = "448d7dc7170c4aff81c2a58c5e07e739"

[vars]
VAPID_PUBLIC_KEY = ""
VAPID_SUBJECT = "mailto:you@example.com"
